[package]
name = "sdl_test"
version = "0.1.0"
authors = ["wws <1274704958@qq.com>"]
build = "build.rs"

[dependencies]
rand = "0.5"
sdl2 = {version = "0.31.0",features = ["gfx","image","unsafe_textures"]}